name: Issues
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Output Issue Related Stuff
        run: echo "${{ toJSON(github.event.issue) }}"
